name: import_path_converter
description: Automatically organize your dart imports
version: 1.0.0
homepage: https://twitter.com/ymgn9314
maintainer: Seiya Yamamoto(@ymgn9314)

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  path: ^1.8.0
  tint: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.7

import_path_converter:
  relative: false # Optional, defaults to false
  ignored_files: # Optional, defaults to []
    - \/lib\/*
